### ISSUE TITLE
Bug | Validation errors testing Leverage first landing steps

### ISSUE THREAD

**Issue by rodriguez-matias** [binbashar/leverage#110] opened 2022-07-13 14:03 UTC
## Description
Getting some error messages  during `$ leverage terraform init` on step **"Deploy Management/Identities layer"**
https://leverage.binbash.com.ar/first-steps/management-account/#identities-layer

`Error: layer configuration doesn´t seem to be valid`

- Checking In `backend.tfvars` the profile name its **"dc-bootstrap"**
- Also check here and it has the same profile.

> $ cat .../.aws/dc/credentials
> [dc-bootstrap]          <---------    
> aws_access_key_id = AKIAXXXXXXXXX2
> aws_secret_access_key = XXXXXXXXXXXXXXX

## Steps to Reproduce
1. Go to :  `$ cd ~/management/global/base-identities/`
2. Run:  `$ leverage terraform init`
3. See error

But using the flag `--skip-validation` , it works :ok:

## Screenshots

![image](https://user-images.githubusercontent.com/65817386/178751777-d8235f74-a7ae-4192-82bd-489d13e583b1.png)

![image](https://user-images.githubusercontent.com/65817386/178751831-49b8fd58-e914-4800-8a30-c6260e35ef80.png)

## Environment
Anything that will help us triage the bug will help. Here are some ideas:
 - macOS v10.15
 - Leverage CLI v1.7.2

**Comment by diego-ojeda-binbash** [comment] 2022-09-05 18:09
Duplicate of #111

**Closed by diego-ojeda-binbash** 2022-09-05 18:09 UTC
Labels: bug
